### ISSUE TITLE
[投票] 关于例句功能的增加

### ISSUE THREAD

**Issue by BailPlus** [BailPlus/bssenglish#4]
我们计划向程序中添加“单词例句”功能。目前已决定在“记忆”模块增加该功能。对于是否要在“默写”模块增加该功能，需要投票决定。
# 效果图
- 记忆模块：
![记忆模块效果图](https://foruda.gitee.com/images/1677927008598414140/29f9e25d_12130568.png "屏幕截图")
- 默写模块：
![默写模块效果图](https://foruda.gitee.com/images/1677926075575899099/10de7c94_12130568.png "屏幕截图")
注：效果图基于 b0a85e87d27c6eb8f4ac057dc94f36d7929c853e ,可能与将来实际效果有所出入。
# 投票方式
在本issue中评论回复。
赞成在“默写”界面增加例句功能的回复`1`，反对的回复`0`。
投票评论只能包含`1`或`0`。其他回复将被视为普通评论，没有投票的效果。
# 截止日期
2023年3月17日。
届时将关闭该issue，后期回复均无效。

**Comment by gfdgd-xi** [comment]
1

**Comment by Cacarot** [comment]
1

**Comment by BailPlus** [comment]
统计结果: 
赞成：2票；反对：0票
----
注：由于学习原因，我准备暂时停更此项目。预计最迟在2024年6月10日复更。敬请谅解。
